### ISSUE TITLE
Báo Cáo File Word & File PDF

### ISSUE THREAD

**Issue by hieuvm68** [hieuvm68/cnpmncn#20]

**Comment by quan1009** [comment]
[baocao10.6.pdf](https://github.com/hieuvm68/cnpmncn/files/6625500/baocao10.6.pdf)
[baocao10.6.docx](https://github.com/hieuvm68/cnpmncn/files/6625502/baocao10.6.docx)

**Comment by quan1009** [comment]
[baocao10.6.docx](https://github.com/hieuvm68/cnpmncn/files/6625508/baocao10.6.docx)
[baocao10.6.pdf](https://github.com/hieuvm68/cnpmncn/files/6625509/baocao10.6.pdf)

**Comment by hieuvm68** [comment]
ô thầy ns f ghi tên sv b ko ổng chém chết h
